image:
  file: .gitpod.dockerfile
ports:
  - port: 3000
    onOpen: open-preview
  - port: 3035
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 6379
    onOpen: ignore
tasks:
  - command: redis-server
  - init: cp .env-gitpod .env
    command: >
      gem install foreman;
      bin/gitpod_setup &&
      bin/gitpod_start
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: true
    addCheck: true
