default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  connect_timeout: 2
  checkout_timeout: 2

development:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', '') %>
  database: gitpod_rails_starter_development

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', '') %>
  database: gitpod_rails_starter_test

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', '') %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: gitpod_rails_starter_production
